# Generated by Django 6.0.5 on 2026-10-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hgnc_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="HGNC ID"
                    ),
                ),
                (
                    "gene_symbol",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Approved symbol"
                    ),
                ),
                (
                    "gene_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Approved name"
                    ),
                ),
                ("previous_symbols", models.JSONField(blank=True, default=list)),
                ("previous_names", models.JSONField(blank=True, default=list)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("mane_select", models.JSONField(blank=True, default=list)),
                ("mane_plus_clinical", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["gene_symbol"],
            },
        ),
    ]
